version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: technomoney-redis
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: technomoney-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: technomoney
      POSTGRES_PASSWORD: technopass
      POSTGRES_DB: technomoney_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./technomoney-auth/docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth:
    build:
      context: ./technomoney-auth
    container_name: technomoney-auth
    env_file:
      - ./technomoney-auth/prod.env
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./technomoney-auth/keys:/app/keys
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -lc "
      node -e \"require('child_process').execSync('npx sequelize-cli db:migrate',{stdio:'inherit'})\" &&
      node \"$${ENTRY_FILE:-dist/server.js}\"
      "

  api:
    build:
      context: ./technomoney-api
    container_name: technomoney-api
    env_file:
      - ./technomoney-api/prod.env
    ports:
      - "4002:4002"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      auth:
        condition: service_started

  profile:
    build:
      context: ./technomoney-profile-api
    container_name: technomoney-profile
    env_file:
      - ./technomoney-profile-api/prod.env
    ports:
      - "4003:4003"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      auth:
        condition: service_started

  payments:
    build:
      context: ./technomoney-payment-api
    container_name: technomoney-payments
    env_file:
      - ./technomoney-payment-api/prod.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      auth:
        condition: service_started

  ia-agent:
    build:
      context: ./technomoney-ia
    container_name: technomoney-ia
    env_file:
      - ./technomoney-ia/prod.env
    ports:
      - "4010:4010"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      auth:
        condition: service_started

  front:
    build:
      context: ./technomoney-app
    container_name: technomoney-front
    env_file:
      - ./technomoney-app/prod.env
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - auth
      - api
      - profile
      - payments

volumes:
  pgdata:
