openapi: 3.1.0
info:
  title: Auth API
  version: "1.0.0"

servers:
  - url: http://localhost:4000/api/auth

security:
  - bearerAuth: []

paths:
  /register:
    post:
      tags: [Auth]
      summary: Cria um novo usu치rio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:    { type: string, example: user@mail.com }
                password: { type: string, example: 123456 }
                username: { type: string, example: johndoe }
      responses:
        "201": { description: Usu치rio criado }
        "400": { description: E-mail ou user duplicado }

  /login:
    post:
      tags: [Auth]
      summary: Autentica usu치rio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:    { type: string }
                password: { type: string }
      responses:
        "200": { description: OK }
        "400": { description: Credenciais inv치lidas }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
